run:
	poetry run python manage.py runserver 0.0.0.0:8000


migrate:
	poetry run python manage.py migrate


createsuperuser:
	poetry run python manage.py createsuperuser

test:
	poetry run python manage.py test


makemigrations:
	poetry run python manage.py makemigrations


