# Generated by Django 6.0.5 on 2026-05-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('broker_title', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('condo', 'Condo')], max_length=50)),
                ('category', models.CharField(choices=[('co-op', 'Co-op for sale'), ('house-for-sale', 'House for sale'), ('house-for-rent', 'House for rent'), ('condo-for-sale', 'Condo for sale'), ('condo-for-rent', 'Condo for rent'), ('multi-family-for-sale', 'Multi-family for sale'), ('multi-family-for-rent', 'Multi-family for rent'), ('townhouse-for-sale', 'Townhouse for sale'), ('townhouse-for-rent', 'Townhouse for rent'), ('pending', 'Pending'), ('contingent', 'Contingent'), ('land-for-sale', 'Land for sale'), ('for-sale', 'For sale'), ('for-rent', 'For rent'), ('foreclosure', 'Foreclosure'), ('condoplex-for-sale', 'Condoplex for sale'), ('condoplex-for-rent', 'Condoplex for rent'), ('coming-soon', 'Coming soon'), ('mobile-home-for-sale', 'Mobile home for sale'), ('mobile-home-for-rent', 'Mobile home for rent')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('beds', models.PositiveIntegerField(blank=True, null=True)),
                ('baths', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('property_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('main_address', models.CharField(blank=True, max_length=255, null=True)),
                ('administrative_area_level_2', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.CharField(choices=[('new-york', 'New York'), ('los-angeles', 'Los Angeles'), ('chicago', 'Chicago'), ('houston', 'Houston'), ('phoenix', 'Phoenix'), ('philadelphia', 'Philadelphia'), ('san-antonio', 'San Antonio'), ('san-diego', 'San Diego'), ('dallas', 'Dallas'), ('san-jose', 'San Jose')], max_length=20)),
                ('sublocality', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('formatted_address', models.CharField(blank=True, max_length=512, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_images/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.home')),
            ],
        ),
    ]
