# Generated by Django 6.0.5 on 2026-05-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("helper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delete_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("daily_rental", "Daily Rental"),
                            ("apartments", "Apartments"),
                            ("commercial_properties", "Commercial Properties"),
                            ("houses", "Houses"),
                            ("lands", "Lands"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("for_sale", "For Sale"),
                            ("for_rent", "For Rent"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("city_center", "City Center"),
                            ("suburbs", "Suburbs"),
                            ("countryside", "Countryside"),
                            ("outside_city", "Outside City"),
                        ],
                        max_length=40,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("area", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
                "db_table": "properties",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Lands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delete_at", models.DateTimeField(blank=True, null=True)),
                ("agrocultural_land", models.BooleanField(default=False)),
                ("residential_land", models.BooleanField(default=False)),
                ("commercial_land", models.BooleanField(default=False)),
                ("road_access", models.BooleanField(default=False)),
                ("water_access", models.BooleanField(default=False)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_details",
                        to="home.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lands",
                "db_table": "lands",
            },
        ),
        migrations.CreateModel(
            name="Houses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delete_at", models.DateTimeField(blank=True, null=True)),
                ("bedrooms", models.IntegerField()),
                ("floor", models.IntegerField()),
                ("number_of_floors", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                (
                    "bathroom_type",
                    models.CharField(
                        choices=[("combined", "Combined"), ("separate", "Separate")],
                        max_length=40,
                    ),
                ),
                (
                    "furnishing_type",
                    models.CharField(
                        choices=[
                            ("furnished", "Furnished"),
                            ("unfurnished", "Unfurnished"),
                            ("semi_furnished", "Semi-Furnished"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "heating_type",
                    models.CharField(
                        choices=[
                            ("central_heating", "Central Heating"),
                            ("individual_heating", "Individual Heating"),
                            ("no_heating", "No Heating"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "cooling_type",
                    models.CharField(
                        choices=[
                            ("central_cooling", "Central Cooling"),
                            ("individual_cooling", "Individual Cooling"),
                            ("no_cooling", "No Cooling"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "parking_type",
                    models.CharField(
                        choices=[
                            ("garage", "Garage"),
                            ("driveway", "Driveway"),
                            ("street_parking", "Street Parking"),
                            ("no_parking", "No Parking"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "building_material_type",
                    models.CharField(
                        choices=[
                            ("brick", "Brick"),
                            ("concrete", "Concrete"),
                            ("wood", "Wood"),
                            ("steel", "Steel"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "renovation_type",
                    models.CharField(
                        choices=[
                            ("renovated", "Renovated"),
                            ("needs_renovation", "Needs Renovation"),
                            ("recently_renovated", "Recently Renovated"),
                            ("no_renovation_needed", "No Renovation Needed"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_details",
                        to="home.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Houses",
                "db_table": "houses",
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delete_at", models.DateTimeField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="property_images/")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Property Images",
                "db_table": "property_images",
            },
        ),
        migrations.CreateModel(
            name="PropertyNearby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nearby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_nearby",
                        to="helper.nearby",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearby",
                        to="home.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Property Nearby",
                "db_table": "property_nearby",
            },
        ),
        migrations.CreateModel(
            name="PropertyUtility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilities",
                        to="home.property",
                    ),
                ),
                (
                    "utility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_utilities",
                        to="helper.utility",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Property Utilities",
                "db_table": "property_utilities",
            },
        ),
    ]
