# Generated by Django 6.0.5 on 2026-05-15 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_propertynearby_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertynearby",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nearby",
                to="home.property",
            ),
        ),
    ]
